// AUTO-GENERATED — do not edit by hand.
// Per-exercise ANIMATED GIFs from ExerciseDB (RapidAPI), downloaded locally
// to client/public/exgif/. 153 exercises. Served statically,
// zero API calls at runtime. Falls back to exerciseImages/line-art if missing.
export const exerciseGifs = {
  "45° Back Extension": "/exgif/1314.gif",
  "Ab Wheel Rollout": "/exgif/0857.gif",
  "Arnold Press": "/exgif/2137.gif",
  "Assault Bike": "/exgif/0003.gif",
  "Assisted Dip Machine": "/exgif/0009.gif",
  "Assisted Pull-Up Machine": "/exgif/0017.gif",
  "Back Squat": "/exgif/1461.gif",
  "Barbell Curl": "/exgif/0031.gif",
  "Barbell Hip Thrust": "/exgif/1409.gif",
  "Barbell Overhead Press": "/exgif/0105.gif",
  "Barbell Row": "/exgif/3017.gif",
  "Barbell Shrug": "/exgif/0095.gif",
  "Barbell Upright Row": "/exgif/0120.gif",
  "Bayesian Cable Curl": "/exgif/0195.gif",
  "Bench Dip": "/exgif/0830.gif",
  "Bent-Over Reverse Fly": "/exgif/0383.gif",
  "Bicycle Crunch": "/exgif/0972.gif",
  "Bulgarian Split Squat": "/exgif/2368.gif",
  "Cable Chest Press": "/exgif/2144.gif",
  "Cable Crossover (High-to-Low)": "/exgif/1270.gif",
  "Cable Crossover (Low-to-High)": "/exgif/1269.gif",
  "Cable Crunch": "/exgif/0175.gif",
  "Cable Curl": "/exgif/0868.gif",
  "Cable Fly": "/exgif/0179.gif",
  "Cable Glute Kickback": "/exgif/0860.gif",
  "Cable Hip Abduction": "/exgif/0710.gif",
  "Cable Lateral Raise": "/exgif/0178.gif",
  "Cable Pull-Through": "/exgif/0196.gif",
  "Cable Rear Delt Fly": "/exgif/0202.gif",
  "Cable Rope Hammer Curl": "/exgif/0165.gif",
  "Cable Shrug": "/exgif/0220.gif",
  "Cable Upright Row": "/exgif/0246.gif",
  "Captain's Chair Leg Raise": "/exgif/2963.gif",
  "Chest Dip": "/exgif/0251.gif",
  "Chest-Supported Row Machine": "/exgif/0581.gif",
  "Chin-Up": "/exgif/1326.gif",
  "Close-Grip Bench Press": "/exgif/2432.gif",
  "Concentration Curl": "/exgif/0297.gif",
  "Conventional Deadlift": "/exgif/0032.gif",
  "Curtsy Lunge": "/exgif/0336.gif",
  "Decline Barbell Bench Press": "/exgif/0033.gif",
  "Decline Dumbbell Press": "/exgif/0301.gif",
  "Decline Push-Up": "/exgif/0279.gif",
  "Decline Sit-Up": "/exgif/0282.gif",
  "Deficit Deadlift": "/exgif/0578.gif",
  "Diamond Push-Up": "/exgif/0283.gif",
  "Dumbbell Bench Press": "/exgif/0289.gif",
  "Dumbbell Fly": "/exgif/0308.gif",
  "Dumbbell Lateral Raise": "/exgif/0334.gif",
  "Dumbbell Overhead Extension": "/exgif/0426.gif",
  "Dumbbell RDL": "/exgif/0300.gif",
  "Dumbbell Shoulder Press": "/exgif/0405.gif",
  "Dumbbell Shrug": "/exgif/0406.gif",
  "Dumbbell Upright Row": "/exgif/0437.gif",
  "EZ-Bar Curl": "/exgif/2404.gif",
  "Elliptical Trainer": "/exgif/2141.gif",
  "Face Pull": "/exgif/0154.gif",
  "Flat Barbell Bench Press": "/exgif/0025.gif",
  "Front Squat": "/exgif/0042.gif",
  "Glute Bridge": "/exgif/3561.gif",
  "Goblet Squat": "/exgif/1760.gif",
  "Good Morning": "/exgif/0044.gif",
  "Hack Squat Machine": "/exgif/0743.gif",
  "Hammer Curl": "/exgif/0313.gif",
  "Hammer Strength Chest Press": "/exgif/0577.gif",
  "Hammer Strength Pulldown": "/exgif/0579.gif",
  "Hammer Strength Row": "/exgif/1348.gif",
  "Hanging Leg Raise": "/exgif/0472.gif",
  "Hip Abduction Machine": "/exgif/0597.gif",
  "Hip Adduction Machine": "/exgif/0598.gif",
  "Incline Barbell Bench Press": "/exgif/0047.gif",
  "Incline Cable Fly": "/exgif/0171.gif",
  "Incline Dumbbell Curl": "/exgif/0318.gif",
  "Incline Dumbbell Fly": "/exgif/0319.gif",
  "Incline Dumbbell Press": "/exgif/0314.gif",
  "Incline Machine Press": "/exgif/1299.gif",
  "Incline Push-Up": "/exgif/0493.gif",
  "Incline Treadmill Walk": "/exgif/3666.gif",
  "Jump Rope": "/exgif/2612.gif",
  "Lat Pulldown (Close Grip)": "/exgif/0974.gif",
  "Lat Pulldown (Wide Grip)": "/exgif/1325.gif",
  "Leaning Cable Lateral Raise": "/exgif/0192.gif",
  "Leg Extension Machine": "/exgif/0585.gif",
  "Leg Press": "/exgif/2287.gif",
  "Leg Press Calf Raise": "/exgif/1385.gif",
  "Lying Leg Curl Machine": "/exgif/0586.gif",
  "Machine Ab Crunch": "/exgif/1452.gif",
  "Machine Back Extension": "/exgif/0573.gif",
  "Machine Chest Press": "/exgif/0576.gif",
  "Machine Hip Thrust": "/exgif/3236.gif",
  "Machine Lat Pulldown": "/exgif/0673.gif",
  "Machine Lateral Raise": "/exgif/0584.gif",
  "Machine Preacher Curl": "/exgif/0592.gif",
  "Machine Shoulder Press": "/exgif/0603.gif",
  "Machine Shrug": "/exgif/0604.gif",
  "Neutral-Grip Lat Pulldown": "/exgif/0818.gif",
  "Nordic Hamstring Curl": "/exgif/0496.gif",
  "Overhead Rope Extension": "/exgif/1724.gif",
  "Pec Deck Machine": "/exgif/0596.gif",
  "Pendlay Row": "/exgif/0574.gif",
  "Pendulum Squat Machine": "/exgif/0755.gif",
  "Plank": "/exgif/0464.gif",
  "Preacher Curl (EZ-Bar)": "/exgif/0452.gif",
  "Pull-Up": "/exgif/0652.gif",
  "Push Press": "/exgif/1700.gif",
  "Rack Pull": "/exgif/0074.gif",
  "Reverse Lunge": "/exgif/0381.gif",
  "Reverse Pec Deck Machine": "/exgif/0602.gif",
  "Romanian Deadlift": "/exgif/0085.gif",
  "Rope Pushdown": "/exgif/0200.gif",
  "Russian Twist": "/exgif/0687.gif",
  "Seated Barbell Press": "/exgif/0091.gif",
  "Seated Cable Row (Close)": "/exgif/0861.gif",
  "Seated Cable Row (Wide)": "/exgif/0218.gif",
  "Seated Calf Raise Machine": "/exgif/0594.gif",
  "Seated Leg Curl Machine": "/exgif/0599.gif",
  "Seated Machine Row": "/exgif/1350.gif",
  "Single-Arm Cable Kickback": "/exgif/1728.gif",
  "Single-Arm Dumbbell Row": "/exgif/0292.gif",
  "Single-Leg Extension": "/exgif/3007.gif",
  "Single-Leg Hip Thrust": "/exgif/1764.gif",
  "Single-Leg Press": "/exgif/0760.gif",
  "Sissy Squat": "/exgif/1489.gif",
  "Skull Crushers": "/exgif/0060.gif",
  "Smith Machine Bench Press": "/exgif/0748.gif",
  "Smith Machine Calf Raise": "/exgif/0763.gif",
  "Smith Machine Deadlift": "/exgif/0752.gif",
  "Smith Machine Hip Thrust": "/exgif/0756.gif",
  "Smith Machine Incline Press": "/exgif/0757.gif",
  "Smith Machine Lunge": "/exgif/1688.gif",
  "Smith Machine Row": "/exgif/0761.gif",
  "Smith Machine Shoulder Press": "/exgif/0766.gif",
  "Smith Machine Shrug": "/exgif/0767.gif",
  "Smith Machine Squat": "/exgif/0770.gif",
  "Smith Machine Upright Row": "/exgif/0775.gif",
  "Spider Curl": "/exgif/1675.gif",
  "Stair Climber": "/exgif/2311.gif",
  "Standard Push-Up": "/exgif/0662.gif",
  "Standing Calf Raise Machine": "/exgif/0605.gif",
  "Stationary Bike": "/exgif/0798.gif",
  "Step-Up": "/exgif/0431.gif",
  "Straight-Arm Pulldown": "/exgif/0238.gif",
  "Straight-Bar Pushdown": "/exgif/0199.gif",
  "Sumo Deadlift": "/exgif/0117.gif",
  "T-Bar Row": "/exgif/0606.gif",
  "Trap Bar Deadlift": "/exgif/0811.gif",
  "Treadmill Run": "/exgif/0685.gif",
  "Triceps Dip Machine": "/exgif/0814.gif",
  "V-Bar Pushdown": "/exgif/0241.gif",
  "Walking Lunge": "/exgif/1460.gif",
  "Weighted Chest Dip": "/exgif/2462.gif",
  "Weighted Hyperextension": "/exgif/0489.gif",
  "Weighted Push-Up": "/exgif/0258.gif"
};
